### PR TITLE
Change install method

### PR DESCRIPTION
**Pull request by raphm4044**
Use 'pipx' instead of 'pip' in the README.md file

### CODE REVIEW

**Comment by sleepy-monax** [comment]
What's the reasoning behind this change ?

**Comment by raphm4044** [comment]
Since pip wants a venv to install something since Python 3.11, it says we can use 'pipx install .' to install a Python app, as cutekit...

**Comment by sleepy-monax** [comment]
@keyboard-slayer need you opinion on this none

**Comment by keyboard-slayer** [comment]
I don't really like the fact that you need to install `pipx`

**Comment by keyboard-slayer** [comment]
Maybe the better solution is doing an easy install script that you can install using `curl | bash`

**Comment by raphm4044** [comment]
Good idea

**Comment by raphm4044** [comment]
A script that creates a Python VEnv in ~/local/lib/python3.11/venv/cutekit, add the CuteKit dependencies in it, install CuteKit in the VEnv, and add VEnv's bin folder in PATH

**Comment by sleepy-monax** [comment]
Oops

**Pull request closed without merging**
